### DISCUSSION TITLE
GUID listed in an `*.asset` file not linking to any file?

### DISCUSSION THREAD

**Discussion by RaenonX** [AssetRipper/AssetRipper#1471] [Q&A]
Related topic of https://github.com/AssetRipper/AssetRipper/issues/1367.

For context, this is mainly for Spine animation file extraction. Each animation will have these files & characteristics:
- `*.png`: Consist of the moving parts of an animation. Can have multiple, with their name listed out in `*.atlas` file.
- `*.atlas`: Consist of some metadata of different moving parts in `*.png`. Readable as text file. Multiple `*.png` files can share the same `*.atlas` file.
- `*.skel`: Some binary file I don't really know how to interpret, but 1 animation will have 1 skeleton file only.

So recently I found that an `*.atlas` file might have connection to 2 files. From the extracted file located at `Assets\Asset_Bundles\e03ea377d350b016d6dcab5720551b53.bundle\sleep-drowse_Atlas.asset`:
```yaml
MonoBehaviour:
  m_ObjectHideFlags: 0
  m_CorrespondingSourceObject: {fileID: 0}
  m_PrefabInstance: {fileID: 0}
  m_PrefabAsset: {fileID: 0}
  m_GameObject: {fileID: 0}
  m_Enabled: 1
  m_EditorHideFlags: 0
  m_Script: {fileID: 11500000, guid: fb6a9381bd1153e90fb3841230adf0c3, type: 3}
  m_Name: sleep-drowse_Atlas
  m_EditorClassIdentifier:
  atlasFile: {fileID: 4900000, guid: 1715ed376186577469cf06f2cf6906a2, type: 3}
  materials:
  - {fileID: 2100000, guid: 93c629575883df94faec0bcc8e1b3405, type: 2}
  - {fileID: 2100000, guid: a28acd46afbcdea478520c930bb874fd, type: 2}
```

The GUID listed as `materials` (`93c629575883df94faec0bcc8e1b3405` and `a28acd46afbcdea478520c930bb874fd`) doesn't seem to link to any files (doing text search in the extracted folder doesn't give any results), is there anything I am missing or any settings I should change so the file would export?

The linked atlas file found using `atlasFile.guid` does show that there are 2 associated files of `sleep-drowse.png` and `sleep-drowse_2.png` in the corresponding `atlas.txt` (see below), which should correspond to `Assets\Asset_Bundles\e03ea377d350b016d6dcab5720551b53.bundle\sleep-drowse_0.png` and `Assets\Asset_Bundles\e03ea377d350b016d6dcab5720551b53.bundle\sleep-drowse_2.png` or `Assets\Asset_Bundles\e03ea377d350b016d6dcab5720551b53.bundle\sleep-drowse_2_0.png`.

(atlas file content of GUID `1715ed376186577469cf06f2cf6906a2`)
```
sleep-drowse.png
size:2048,2048
filter:Linear,Linear
...

sleep-drowse_2.png
size:2048,2048
filter:Linear,Linear
...
```

Attaching the link for the whole data dump (~500 MB) to not missing any key files: https://drive.google.com/file/d/1WFIJGEt_aJa8vuU8b5gv6f-7wxumOw5U/view?usp=sharing
