### ISSUE TITLE
[Enhancement]: Timeline/Cinemachine Support

### ISSUE THREAD

**Issue by Zbuffers** [AssetRipper/AssetRipper#1004]
### Describe the new feature or enhancement

Hi,

Just though I would mention it here, for the record.

The Timeline PlayableDirector component has mainly 3 properties (there are more in reality):
- timeline asset reference -> m_PlayableAsset (pptr to the timeline asset)
- scene bindings references -> m_SceneBindings (list of key/value pairs where key is the reference to the clip/track of the timeline, and Value is the fileID of the component in the scene)
- Exposed references -> m_ExposedReferences (list of  ID/FileID of scene components)

The Exposed references is the one that needs attention (fix)
As an exemple (extract from a unity scene)

```
--- !u!320 &45180
PlayableDirector:
  m_ObjectHideFlags: 0
  m_CorrespondingSourceObject: {fileID: 0}
  m_PrefabInstance: {fileID: 0}
  m_PrefabAsset: {fileID: 0}
  m_GameObject: {fileID: 3274}
  m_Enabled: 1
  serializedVersion: 3
  m_PlayableAsset: {fileID: 11400000, guid: 824297fea4b92af4ba156c57c65732b1, type: 2}
  m_InitialState: 0
  m_WrapMode: 2
  m_DirectorUpdateMode: 1
  m_InitialTime: 0
  m_SceneBindings:
  - key: {fileID: 11400000, guid: 13544b2e2262d2748aba584a8158c21c, type: 2}
    value: {fileID: 49294}
  - key: {fileID: 11400000, guid: f68f54cc31fe751408a55a54451a7f97, type: 2}
    value: {fileID: 43580}
  - key: {fileID: 11400000, guid: 80f7fab9cabab45439cf1d080f7c394e, type: 2}
    value: {fileID: 49294}
  - key: {fileID: 11400000, guid: d3fa060cd1addd14298ec9d109914c2f, type: 2}
    value: {fileID: 43580}
  m_ExposedReferences:
    m_References:
    - 1498453719: {fileID: 45802
```

and here is an extract from the corresponding cinemachineShot:
```
  m_Name: CinemachineShot_103
  m_EditorClassIdentifier: 
  DisplayName: 
  VirtualCamera:
    exposedName: 1498453719
    defaultValue: {fileID: 0}
```
As you can see, the exposed references do the binding between the cinemachine shot in the timeline, and the virtualCinemachine Camera component in the scene.

Unfortunately, AssetRipper does not export those ExposedReferences...
Since timeline and cinemachine are widely used, I think it would be a great addition.

Kind regards,
Z

**Comment by ds5678** [comment]
That's because Unity had inconsistent serialization for `ExposedReferences` between the release and editor type trees. When that happens, I have to split the field into two during source generation.

**Comment by Zbuffers** [comment]
Holly Cow !!
You are just the DOAT ;) ;) :)
(Dev Of All Times ;))

Thanks A million times for fixing this so quickly !!!
Off I go to test this ;)

Once again,
THANKS !!!
Z

**Comment by ds5678** [comment]
You're welcome Z

**Comment by ds5678** [comment]
Let me know how it goes.

**Comment by Zbuffers** [comment]
Just tested this, using the latest commit.
Using a Release compile, I have a crash while reading the game (see Release Log attached)
Same with a Debug build (see Debug log attached)

Game: Sonority
Unity Version: 2020.3.35

Should you need me to make more tests and or try stuff, just ask ;)

[Release AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/12440290/Release.AssetRipper.log)
[Debug AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/12440292/Debug.AssetRipper.log)

**Comment by ds5678** [comment]
Fixed

**Comment by Zbuffers** [comment]
Yeah ;)
No more crash upon reading the game ;) ;) ;) (release compile)
Give me a few minutes to report about the exported result.

**Comment by Zbuffers** [comment]
Why  I am hearing a Tina turner song ? (see link at the end ;)

As far as I can tell (I didn't open the project in Unity), all references are indeed exported and look good !!!

cinemachine shot:

```
  m_Name: CinemachineShot(Clone)
  m_EditorClassIdentifier:
  DisplayName:
  VirtualCamera:
    exposedName: -1639255524 <- Virtual Camera reference
    defaultValue: {fileID: 0}
```

extract from unity scene:

```
  m_ExposedReferences:
    m_References:
    - -2134947967: {fileID: 25950}
    - -2026608836: {fileID: 25929}
    - -2023150805: {fileID: 25950}
    - -1743612621: {fileID: 0}
    - -1735024402: {fileID: 6281}
    - -1639255524: {fileID: 25929} <- YEAH its there !!! ;) and fileID is indeed a CM virtual camera component, seems all good
    - -1368986162: {fileID: 26601}
    - -481282040: {fileID: 25950}
    - -221305317: {fileID: 25930}
    - -177651717: {fileID: 25930}
    - 54586570: {fileID: 25930}
    - 339738701: {fileID: 25950}
    - 684670340: {fileID: 26601}
    - 1180803429: {fileID: 26601}
    - 1353715025: {fileID: 25950}
    - 1453547969: {fileID: 1009027848735160, guid: 59e7dab0d18953b429de51b93669a775, type: 2}
    - 1695473797: {fileID: 0}
    - 1813565487: {fileID: 25930}
```
I will continue to check with the full game, and other games.

Just for you ;)
https://youtu.be/nTBFy4rc6Lw?t=66
Cheers,
Z
