### ISSUE TITLE
[Bug]: Missing SerializedVersion for Type Tree MonoBehaviour Structures

### ISSUE THREAD

**Issue by Zbuffers** [AssetRipper/AssetRipper#1048]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which Unity version did this occur on?

2021.3.30,
although I think it applies to all versions...

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Hi,

I noticed that all Unity Rect properties are missing a serializedVersion property.
The values are read and exported fine (x, y, width, height), but the problem is that after saving the asset in unity, (scene, prefab or asset), Unity resets the values to 0 for x, y, width, and height when the serialiedversion is missing. stupid unity ... ;)

Example (from a RAW Texture):
```
  m_UVRect:
    x: 0
    y: 0
    width: 1
    height: 1
```
Should be:
```
  m_UVRect:
    serializedVersion: 2  <-- Adding this fixes it
    x: 0
    y: 0
    width: 1
    height: 1
```

Adding the 'serializedVersion: 2' fixes it (I did a quick (search&Replace) in all relevant assets (scene, prefabs and assets) and all is ok now ;)

Kind regards,
Z

**Comment by ds5678** [comment]
My source generated code looks like it should already have that:
```cs
	public override YamlNode ExportYamlEditor(IExportContainer container)
	{
		YamlMappingNode yamlMappingNode = new YamlMappingNode();
		yamlMappingNode.AddSerializedVersion(2);
		yamlMappingNode.Add(new YamlScalarNode("x"), ExportYamlEditorMethods.ExportYamlEditor_Single(m_X, container));
		yamlMappingNode.Add(new YamlScalarNode("y"), ExportYamlEditorMethods.ExportYamlEditor_Single(m_Y, container));
		yamlMappingNode.Add(new YamlScalarNode("width"), ExportYamlEditorMethods.ExportYamlEditor_Single(m_Width, container));
		yamlMappingNode.Add(new YamlScalarNode("height"), ExportYamlEditorMethods.ExportYamlEditor_Single(m_Height, container));
		return yamlMappingNode;
	}
```
How could this be happening?

**Comment by ds5678** [comment]
Oh, I think I see what's going on. I think that's `RectInt`. I'm seeing that it has serialized version 1 in the source generation. This happened because it's not in the type trees, but instead an injected type. I'll get that fixed before the next release.

**Comment by ds5678** [comment]
Thank you for the report!

**Comment by ds5678** [comment]
I fixed this in the source generation and confirmed that none of the other injected types have this issue.

**Comment by Zbuffers** [comment]
Isn't RectInt for int values ?
This also applies to Rect with float values.

Extract from a scene containing Raw images I had to modify:

```
  m_UVRect:
    x: 0.01
    y: 0.67
    width: 0.2392
    height: 0.371
```
had to be changed to:
```
  m_UVRect:
    serializedVersion: 2
    x: 0.01
    y: 0.67
    width: 0.2392
    height: 0.371
```
