### ISSUE TITLE
[Bug]: Material properties data are exported incorrectly

### ISSUE THREAD

**Issue by GZHYBFHHJ** [AssetRipper/AssetRipper#1136]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest alpha-build of AssetRipper.

### Which release are you using?

Windows x64

### Which Unity version did this occur on?

3.5.3

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Material properties data is incorrectly exported as:
```
  m_SavedProperties:
    serializedVersion: 2
    m_TexEnvs:
    - first:
        name: _MainTex
      second:
        ...
    - first:
        name: _Tex2
      second:
        ...
    m_Floats: {}
    m_Colors:
    - first:
        name: _Color
      second: ...
```
It cannot be parsed properly by Unity 4

It should be:
```
  m_SavedProperties:
    serializedVersion: 2
    m_TexEnvs:
      data:
        first:
          name: _MainTex
        second:
          ...
      data:
        first:
          name: _Tex2
        second:
          ...
    m_Floats: {}
    m_Colors:
      data:
        first:
          name: _Color
        second: ...
```
