### ISSUE TITLE
[Enhancement]: IPPtrCurve.Flags

### ISSUE THREAD

**Issue by Zbuffers** [AssetRipper/AssetRipper#1158]
Hi,

I noticed that animations clips using material animation (change the material itself, not properties) do not have the correct flag set.
Unity fails to read them...

example:
```
...
m_PPtrCurves:
  - serializedVersion: 2
    curve:
    - time: 0
      value: {fileID: 2100000, guid: 81dc2c8d64d38554a918f36f088f928a, type: 2}
    - time: 0.05
      value: {fileID: 2100000, guid: e42f9f51d8a42fd47a29a2bdb3907704, type: 2}
    - time: 0.15
      value: {fileID: 2100000, guid: e42f9f51d8a42fd47a29a2bdb3907704, type: 2}
    attribute: m_Materials.Array.data[0]
    path: Rod
    classID: 23
    script: {fileID: 0}
    flags: 0  <- INCORRECTT FLAG HERE, SHOULD BE 2
  m_SampleRate: 60
  m_WrapMode: 0
  m_Bounds:
    m_Center: {x: 0, y: 0, z: 0}
    m_Extent: {x: 0, y: 0, z: 0}
...
```

Just setting this flag to 2 makes Unity happy, and the clip worls fine (I have no idea what this flag is...)
I found  this after making a dummy animation  clip and comparing the YAML.

using Unity 2022.3

I Hope this can be usefull ;)
Regards,
Z

**Comment by ds5678** [comment]
Apparently, this is new in `2022.2`. I would be interested to know what the enum for these flags is.

**Comment by ds5678** [comment]
Might be this:
```cs
/// <summary>
/// Full Name: EditorCurveBinding.Flags
/// </summary>
[Flags]
public enum EditorCurveBindingFlags : uint
{
	/// <summary>
	/// Original name: kNone
	/// </summary>
	None = 0u,
	/// <summary>
	/// Original name: kDiscrete
	/// </summary>
	Discrete = 1u,
	/// <summary>
	/// Original name: kPPtr
	/// </summary>
	PPtr = 2u,
	/// <summary>
	/// Original name: kSerializeReference
	/// </summary>
	SerializeReference = 4u,
	/// <summary>
	/// Original name: kPhantom
	/// </summary>
	Phantom = 8u,
	/// <summary>
	/// Original name: kUnknow
	/// </summary>
	Unknow = 0x10u
}
```
IFloatCurve also has this new field.

**Comment by Zbuffers** [comment]
Hi, 
Actually, I checked another project  (2022.3.5) and it seams it concerns ALL PPTr curves...
here is another example for a sprite animation:

```
  m_PPtrCurves:
  - serializedVersion: 2
    curve:
    - time: 0
      value: {fileID: 21300000, guid: dfa4a0be3ba0c694fbd5136b1442f929, type: 3}
    - time: 0.25
      value: {fileID: 21300000, guid: 7eb0e4e649d19b144ae0d822c4b707af, type: 3}
    - time: 0.5
      value: {fileID: 21300000, guid: 5914fb66e81adca4ea29f85bd4962668, type: 3}
    - time: 0.75
      value: {fileID: 21300000, guid: 987f8059ae8f90d48b45419526cfcb61, type: 3}
    - time: 1
      value: {fileID: 21300000, guid: 987f8059ae8f90d48b45419526cfcb61, type: 3}
    attribute: m_Sprite
    path:
    classID: 212
    script: {fileID: 0}
    flags: 2 <- SAME FLAG HERE I NEED TO CHANGE TO 2
```
