### ISSUE TITLE
[Bug]: AnimationClip if frame 0 has pptrCurve the keyFrame will lost

### ISSUE THREAD

**Issue by 1260zqs** [AssetRipper/AssetRipper#1190]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

normal project assetbundle build

### Which Unity version did this occur on?

unity 2021.3.25f1_838635431df6 

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

i create a animation clip, bind UnityEngine.UI.Image.m_Sprite at frame 0, after dump a keyframe was lost. 
i also find a function public float CalculateNextInSlope(float deltaTime, float nextValue) if use double to calc the number, result will more closet to orign file value (i tested few files), an other thing i think if OutSlope/InSlope less than 0.0001f it should be zero when add AddTransformCurve.

### Relevant log output

------------AssetRipper dump--------------
```yaml
%YAML 1.1
%TAG !u! tag:unity3d.com,2011:
--- !u!74 &7400000
AnimationClip:
  serializedVersion: 6
  m_ObjectHideFlags: 0
  m_CorrespondingSourceObject: {m_FileID: 0, m_PathID: 0}
  m_PrefabInstance: {m_FileID: 0, m_PathID: 0}
  m_PrefabAsset: {m_FileID: 0, m_PathID: 0}
  m_Name: TestAnimation
  m_Legacy: 0
  m_Compressed: 0
  m_UseHighQualityCurve: 1
  m_RotationCurves: []
  m_CompressedRotationCurves: []
  m_EulerCurves: []
  m_PositionCurves: []
  m_ScaleCurves: []
  m_FloatCurves:
  - curve:
      serializedVersion: 2
      m_Curve:
      - serializedVersion: 3
        time: 0.016666668
        value: 1
        inSlope: 0
        outSlope: 0
        tangentMode: 0
        weightedMode: 0
        inWeight: 0.33333334
        outWeight: 0.33333334
      - serializedVersion: 3
        time: 0.033333335
        value: 2
        inSlope: 0
        outSlope: 0
        tangentMode: 0
        weightedMode: 0
        inWeight: 0.33333334
        outWeight: 0.33333334
      m_PreInfinity: 2
      m_PostInfinity: 2
      m_RotationOrder: 4
    attribute: script_0x7822D856_UsmorHH
    path: Canvas/Image
    classID: 114
    script: {m_FileID: 0, m_PathID: -7030229213176759517}
  m_PPtrCurves: []
  m_SampleRate: 60
  m_WrapMode: 0
  m_Bounds:
    m_Center: {x: 0, y: 0, z: 0}
    m_Extent: {x: 0, y: 0, z: 0}
  m_ClipBindingConstant:
    genericBindings:
    - serializedVersion: 2
      path: 335570237
      attribute: 2015549526
      script: {m_FileID: 0, m_PathID: -7030229213176759517}
      typeID: 114
      customType: 0
      isPPtrCurve: 1
    pptrCurveMapping:
    - {m_FileID: 0, m_PathID: -7781616155096740974}
    - {m_FileID: 0, m_PathID: 4709536451605459540}
    - {m_FileID: 0, m_PathID: 4499502728554349259}
  m_AnimationClipSettings:
    serializedVersion: 2
    m_AdditiveReferencePoseClip: {m_FileID: 0, m_PathID: 0}
    m_AdditiveReferencePoseTime: 0
    m_StartTime: 0
    m_StopTime: 0.050000004
    m_OrientationOffsetY: 0
    m_Level: 0
    m_CycleOffset: 2.13
    m_HasAdditiveReferencePose: 0
    m_LoopTime: 1
    m_LoopBlend: 1
    m_LoopBlendOrientation: 0
    m_LoopBlendPositionY: 0
    m_LoopBlendPositionXZ: 0
    m_KeepOriginalOrientation: 0
    m_KeepOriginalPositionY: 1
    m_KeepOriginalPositionXZ: 0
    m_HeightFromFeet: 0
    m_Mirror: 0
  m_EditorCurves: []
  m_EulerEditorCurves: []
  m_HasGenericRootTransform: 0
  m_HasMotionFloatCurves: 0
  m_Events: []
```
-------------Origin file-------------
```yaml
%YAML 1.1
%TAG !u! tag:unity3d.com,2011:
--- !u!74 &7400000
AnimationClip:
  m_ObjectHideFlags: 0
  m_CorrespondingSourceObject: {fileID: 0}
  m_PrefabInstance: {fileID: 0}
  m_PrefabAsset: {fileID: 0}
  m_Name: TestAnimation
  serializedVersion: 6
  m_Legacy: 0
  m_Compressed: 0
  m_UseHighQualityCurve: 1
  m_RotationCurves: []
  m_CompressedRotationCurves: []
  m_EulerCurves: []
  m_PositionCurves: []
  m_ScaleCurves: []
  m_FloatCurves: []
  m_PPtrCurves:
  - curve:
    - time: 0
      value: {fileID: -6842809076195994343, guid: d6b9b7cd5eb467544990e66589fc78b6,
        type: 3}
    - time: 0.016666668
      value: {fileID: -7362514669110110951, guid: d6b9b7cd5eb467544990e66589fc78b6,
        type: 3}
    - time: 0.033333335
      value: {fileID: -1568220465019169511, guid: d6b9b7cd5eb467544990e66589fc78b6,
        type: 3}
    attribute: m_Sprite
    path: Canvas/Image
    classID: 114
    script: {fileID: 11500000, guid: fe87c0e1cc204ed48ad3b37840f39efc, type: 3}
  m_SampleRate: 60
  m_WrapMode: 0
  m_Bounds:
    m_Center: {x: 0, y: 0, z: 0}
    m_Extent: {x: 0, y: 0, z: 0}
  m_ClipBindingConstant:
    genericBindings:
    - serializedVersion: 2
      path: 335570237
      attribute: 2015549526
      script: {fileID: 11500000, guid: fe87c0e1cc204ed48ad3b37840f39efc, type: 3}
      typeID: 114
      customType: 0
      isPPtrCurve: 1
    pptrCurveMapping:
    - {fileID: -6842809076195994343, guid: d6b9b7cd5eb467544990e66589fc78b6, type: 3}
    - {fileID: -7362514669110110951, guid: d6b9b7cd5eb467544990e66589fc78b6, type: 3}
    - {fileID: -1568220465019169511, guid: d6b9b7cd5eb467544990e66589fc78b6, type: 3}
  m_AnimationClipSettings:
    serializedVersion: 2
    m_AdditiveReferencePoseClip: {fileID: 0}
    m_AdditiveReferencePoseTime: 0
    m_StartTime: 0
    m_StopTime: 0.050000004
    m_OrientationOffsetY: 0
    m_Level: 0
    m_CycleOffset: 2.13
    m_HasAdditiveReferencePose: 0
    m_LoopTime: 1
    m_LoopBlend: 1
    m_LoopBlendOrientation: 0
    m_LoopBlendPositionY: 0
    m_LoopBlendPositionXZ: 0
    m_KeepOriginalOrientation: 0
    m_KeepOriginalPositionY: 1
    m_KeepOriginalPositionXZ: 0
    m_HeightFromFeet: 0
    m_Mirror: 0
  m_EditorCurves: []
  m_EulerEditorCurves: []
  m_HasGenericRootTransform: 0
  m_HasMotionFloatCurves: 0
  m_Events: []
```
