### ISSUE TITLE
[Question]:  2d Array Texture`s and missing link in mesh to LightingData

### ISSUE THREAD

**Issue by Gyron777** [AssetRipper/AssetRipper#1790]
### Question

Hello, I unpacked a mobile game Static Shift Racing, and this game using for the Locations Maps textures in the 2dArray format. Neither the shader nor the material data contains any mention of SliceID, it’s possible that AssetRipper doesn’t yet support this type of data correctly. How can I extract the location objects along with their textures and mesh support LightMaps?

Previously, I hadn’t encountered games that use 2DArray for optimization purposes. 

The shader has input data of this type: 
```
Shader "SSR/Uber Shader" {
	Properties {
		[HideInInspector] _AlphaCutoff ("Alpha Cutoff ", Range(0, 1)) = 0.5
		[HideInInspector] _EmissionColor ("Emission Color", Vector) = (1,1,1,1)
		[NoScaleOffset] _TextureInput ("Texture Input", 2D) = "white" {}
		[HideInInspector] _TextureArrayInput ("TextureArrayInput", 2DArray) = "white" {}
		[Toggle(_UNLIT_ON)] _Unlit ("Unlit", Float) = 0
		[Header(Regular Properties)] [KeywordEnum(Simple,Shiny,Metal)] _LightType ("LightType", Float) = 0
		[HideInInspector] _texcoord ("", 2D) = "white" {}
		[HideInInspector] _QueueOffset ("_QueueOffset", Float) = 0
		[HideInInspector] _QueueControl ("_QueueControl", Float) = -1
		[HideInInspector] [NoScaleOffset] unity_Lightmaps ("unity_Lightmaps", 2DArray) = "" {}
		[HideInInspector] [NoScaleOffset] unity_LightmapsInd ("unity_LightmapsInd", 2DArray) = "" {}
		[HideInInspector] [NoScaleOffset] unity_ShadowMasks ("unity_ShadowMasks", 2DArray) = "" {}
		[ToggleOff] [HideInInspector] _ReceiveShadows ("Receive Shadows", Float) = 1
	}
```

Material has the data:

```
%YAML 1.1
%TAG !u! tag:unity3d.com,2011:
--- !u!21 &2100000
Material:
  serializedVersion: 8
  m_ObjectHideFlags: 0
  m_CorrespondingSourceObject: {fileID: 0}
  m_PrefabInstance: {fileID: 0}
  m_PrefabAsset: {fileID: 0}
  m_Name: CombinedMaterial-19
  m_Shader: {fileID: 4800000, guid: 8dc43500d21a89143a440bf84f3e0e10, type: 3}
  m_ValidKeywords:
  - _LIGHTTYPE_SIMPLE
  - _SSR_COMBINED_T2DARRAY
  m_InvalidKeywords:
  - _INPUTTYPE_TEXTURE
  m_LightmapFlags: 4
  m_EnableInstancingVariants: 0
  m_DoubleSidedGI: 0
  m_CustomRenderQueue: -1
  stringTagMap: {}
  disabledShaderPasses: []
  m_SavedProperties:
    serializedVersion: 3
    m_TexEnvs:
      _TextureArrayInput:
        m_Texture: {fileID: 18700000, guid: b23e9c2604f6f5e45816ad334ebca2b0, type: 3}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
      _TextureInput:
        m_Texture: {fileID: 0}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
      _texcoord:
        m_Texture: {fileID: 0}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
      unity_Lightmaps:
        m_Texture: {fileID: 0}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
      unity_LightmapsInd:
        m_Texture: {fileID: 0}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
      unity_ShadowMasks:
        m_Texture: {fileID: 0}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    m_Ints: {}
    m_Floats:
      _AlphaClip: 0
      _AlphaCutoff: 0.5
      _Blend: 0
      _BumpScale: 1
      _ClearCoatMask: 0
      _ClearCoatSmoothness: 0
      _Cull: 2
      _Cutoff: 0.5
      _DetailAlbedoMapScale: 1
      _DetailNormalMapScale: 1
      _DstBlend: 0
      _EnvironmentReflections: 1
      _GlossMapScale: 0
      _Glossiness: 0
      _GlossyReflections: 0
      _InputType: 1
      _LightType: 0
      _Metallic: 0
      _OcclusionStrength: 1
      _Parallax: 0.005
      _QueueControl: 0
      _QueueOffset: 0
      _ReceiveShadows: 1
      _Smoothness: 0.5
      _SmoothnessTextureChannel: 0
      _SpecularHighlights: 1
      _SrcBlend: 1
      _Surface: 0
      _Unlit: 0
      _WorkflowMode: 1
      _ZWrite: 1
    m_Colors:
      _BaseColor: {r: 1, g: 1, b: 1, a: 1}
      _Color: {r: 1, g: 1, b: 1, a: 1}
      _ColorInput: {r: 0, g: 0, b: 0, a: 0}
      _EmissionColor: {r: 0, g: 0, b: 0, a: 1}
      _SpecColor: {r: 0.19999996, g: 0.19999996, b: 0.19999996, a: 1}
  m_BuildTextureStacks: []

```

### Are you sure you want to clutter the issues section?

Yes, I acknowledge that my question may be ignored because I am not following directions.
