### ISSUE TITLE
[Enhancement]: Texture2DArray Image Export

### ISSUE THREAD

**Issue by ds5678** [AssetRipper/AssetRipper#425]
### Overview

`Texture2DArray`s are an array of individual textures, so they can be exported as a flipbook image file.

### Output Format

The exported file can be in any image file format, but must be a single image. Individual frames are oriented in the image like this:

```
0 1 2
3 4 5
```

Although any ratio where width times height equals frame count is correct, ideally the export would follow these rules:
* width * height = count
* width and height should be as close as possible
* width >= height

### Documentation

* https://docs.unity3d.com/Manual/class-Texture2DArray.html
* https://docs.unity3d.com/Manual/class-TextureImporter.html
* https://docs.unity3d.com/ScriptReference/Texture2DArray.html
* https://blog.unity.com/technology/free-vfx-image-sequences-flipbooks

### Meta File

In order for correct references to be applied, a meta file must be created for each `Texture2DArray`. They use `TextureImporter` when not exported as yaml. Here is an example `2022.1.4f1` meta file:
```
fileFormatVersion: 2
guid: 00b25527c4b91a749b2e0495a8dc61dd
TextureImporter:
  internalIDToNameTable: []
  externalObjects: {}
  serializedVersion: 11
  mipmaps:
    mipMapMode: 0
    enableMipMap: 1
    sRGBTexture: 1
    linearTexture: 0
    fadeOut: 0
    borderMipMap: 0
    mipMapsPreserveCoverage: 0
    alphaTestReferenceValue: 0.5
    mipMapFadeDistanceStart: 1
    mipMapFadeDistanceEnd: 3
  bumpmap:
    convertToNormalMap: 0
    externalNormalMap: 0
    heightScale: 0.25
    normalMapFilter: 0
    flipGreenChannel: 0
  isReadable: 0
  streamingMipmaps: 0
  streamingMipmapsPriority: 0
  vTOnly: 0
  ignoreMasterTextureLimit: 0
  grayScaleToAlpha: 0
  generateCubemap: 6
  cubemapConvolution: 0
  seamlessCubemap: 0
  textureFormat: 1
  maxTextureSize: 2048
  textureSettings:
    serializedVersion: 2
    filterMode: 1
    aniso: 1
    mipBias: 0
    wrapU: 0
    wrapV: 0
    wrapW: 0
  nPOTScale: 1
  lightmap: 0
  compressionQuality: 50
  spriteMode: 0
  spriteExtrude: 1
  spriteMeshType: 1
  alignment: 0
  spritePivot: {x: 0.5, y: 0.5}
  spritePixelsToUnits: 100
  spriteBorder: {x: 0, y: 0, z: 0, w: 0}
  spriteGenerateFallbackPhysicsShape: 1
  alphaUsage: 1
  alphaIsTransparency: 0
  spriteTessellationDetail: -1
  textureType: 0
  textureShape: 4
  singleChannelComponent: 0
  flipbookRows: 5
  flipbookColumns: 5
  maxTextureSizeSet: 0
  compressionQualitySet: 0
  textureFormatSet: 0
  ignorePngGamma: 0
  applyGammaDecoding: 0
  swizzle: 50462976
  platformSettings:
  - serializedVersion: 3
    buildTarget: DefaultTexturePlatform
    maxTextureSize: 2048
    resizeAlgorithm: 0
    textureFormat: -1
    textureCompression: 1
    compressionQuality: 50
    crunchedCompression: 0
    allowsAlphaSplitting: 0
    overridden: 0
    androidETC2FallbackOverride: 0
    forceMaximumCompressionQuality_BC6H_BC7: 0
  - serializedVersion: 3
    buildTarget: Standalone
    maxTextureSize: 2048
    resizeAlgorithm: 0
    textureFormat: -1
    textureCompression: 1
    compressionQuality: 50
    crunchedCompression: 0
    allowsAlphaSplitting: 0
    overridden: 0
    androidETC2FallbackOverride: 0
    forceMaximumCompressionQuality_BC6H_BC7: 0
  - serializedVersion: 3
    buildTarget: Server
    maxTextureSize: 2048
    resizeAlgorithm: 0
    textureFormat: -1
    textureCompression: 1
    compressionQuality: 50
    crunchedCompression: 0
    allowsAlphaSplitting: 0
    overridden: 0
    androidETC2FallbackOverride: 0
    forceMaximumCompressionQuality_BC6H_BC7: 0
  spriteSheet:
    serializedVersion: 2
    sprites: []
    outline: []
    physicsShape: []
    bones: []
    spriteID: 
    internalID: 0
    vertices: []
    indices: 
    edges: []
    weights: []
    secondaryTextures: []
    nameFileIdTable: {}
  spritePackingTag: 
  pSDRemoveMatte: 0
  userData: 
  assetBundleName: 
  assetBundleVariant: 
```

The relevant fields are:
* `textureShape` must be 4 (added in `5.5.0`)
* `flipbookRows` (added in `2020.2.0`)
* `flipbookColumns` (added in `2020.2.0`)

`flipbookRows` and `flipbookColumns` are not available before `2020.2.0` because Unity did not support importing image files as `Texture2DArray` before then. Only yaml `Texture2DArray` assets were supported. As such, using this on versions before `2020.2.0` will result in broken references.
