### ISSUE TITLE
[Bug]: Missing `outline` for image sprites

### ISSUE THREAD

**Issue by lmachens** [AssetRipper/AssetRipper#525]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Linux x64

### Which game did this occur on?

[Songs of Conquest](https://steamdb.info/app/867210/)

### Which Unity version did this occur on?

Unity 2020.3.24

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Hi, thank you for this great project!

In v0.2.0.3, the sprite meta files contained `internalIDToNameTable` and `spriteSheet` with details about the rect and outline of an image.
Example (`ArtifactAtlas.png.meta`):

```yml
  spriteSheet:
    serializedVersion: 2
    sprites:
    - serializedVersion: 2
      name: Glimmergloves_Default_1
      rect:
        serializedVersion: 2
        x: 234
        y: 259
        width: 30
        height: 28
      alignment: 9
      pivot: {x: 0.5, y: -0.035714287}
      border: {x: 0, y: 0, z: 0, w: 0}
      outline:
      - - {x: -15, y: -14}
        - {x: -15, y: 14}
        - {x: 15, y: 14}
        - {x: 15, y: -14}
      physicsShape: []
      tessellationDetail: 0
      bones: []
      spriteID: 1a4e6a083c3742dfb05e5f6a00d7ae1f
      internalID: 21300000
      vertices:
      - {x: 0, y: 43}
      - {x: 30, y: 43}
      - {x: 0, y: 15}
      - {x: 30, y: 15}
      indices:
      - 0
      - 1
      - 2
      - 2
      - 1
      - 3
      edges: []
      weights: []
```

With v0.2.3.0, this information is in a different file (`Glimmergloves_Default_1.asset`), including information about the name or rect. But the outline is missing:

```yml
%YAML 1.1
%TAG !u! tag:unity3d.com,2011:
--- !u!213 &21300000
Sprite:
  m_ObjectHideFlags: 0
  m_CorrespondingSourceObject: {fileID: 0}
  m_PrefabInstance: {fileID: 0}
  m_PrefabAsset: {fileID: 0}
  m_Name: Glimmergloves_Default_1
  m_Rect:
    serializedVersion: 2
    x: 234
    y: 259
    width: 30
    height: 28
  m_Offset: {x: 0, y: 0}
  m_Border: {x: 0, y: 0, z: 0, w: 0}
  m_PixelsToUnits: 32
  m_Pivot: {x: 0.5, y: -0.035714287}
  m_Extrude: 1
  m_IsPolygon: 0
  m_AtlasName:
  m_PackingTag:
  m_RenderDataKey:
    5825b71c5406d4788ad25c797bf923e9: -9159657145753931571
  m_AtlasTags: []
  m_SpriteAtlas: {fileID: 0}
  m_RD:
    serializedVersion: 3
    texture: {fileID: 2800000, guid: 2462bce0f7e62ed4f8a3ebb7fdbeaa21, type: 3}
    alphaTexture: {fileID: 0}
    secondaryTextures: []
    m_SubMeshes:
    - serializedVersion: 2
      firstByte: 0
      indexCount: 6
      topology: 0
      baseVertex: 0
      firstVertex: 0
      vertexCount: 4
      localAABB:
        m_Center: {x: 0, y: 0, z: 0}
        m_Extent: {x: 0, y: 0, z: 0}
    m_IndexBuffer: 000001000200020001000300
    m_VertexData:
      serializedVersion: 3
      m_VertexCount: 4
      m_Channels:
      - stream: 0
        offset: 0
        format: 0
        dimension: 3
      - stream: 0
        offset: 0
        format: 0
        dimension: 0
      - stream: 0
        offset: 0
        format: 0
        dimension: 0
      - stream: 0
        offset: 0
        format: 0
        dimension: 0
      - stream: 1
        offset: 0
        format: 0
        dimension: 2
      - stream: 0
        offset: 0
        format: 0
        dimension: 0
      - stream: 0
        offset: 0
        format: 0
        dimension: 0
      - stream: 0
        offset: 0
        format: 0
        dimension: 0
      - stream: 0
        offset: 0
        format: 0
        dimension: 0
      - stream: 0
        offset: 0
        format: 0
        dimension: 0
      - stream: 0
        offset: 0
        format: 0
        dimension: 0
      - stream: 0
        offset: 0
        format: 0
        dimension: 0
      - stream: 0
        offset: 0
        format: 0
        dimension: 0
      - stream: 0
        offset: 0
        format: 0
        dimension: 0
      m_DataSize: 80
      _typelessdata: 0000f0be0000683f000000000000f03e0000683f000000000000f0be0000003d000000000000f03e0000003d000000000000000000000000000000000000000000000000000000000000000000000000
    m_Bindpose: []
    textureRect:
      serializedVersion: 2
      x: 234
      y: 259
      width: 30
      height: 28
    textureRectOffset: {x: 0, y: 0}
    atlasRectOffset: {x: -1, y: -1}
    settingsRaw: 0
    uvTransform: {x: 32, y: 249, z: 32, w: 258}
    downscaleMultiplier: 1
  m_AtlasRD:
    serializedVersion: 3
    texture: {fileID: 0}
    alphaTexture: {fileID: 0}
    secondaryTextures: []
    m_SubMeshes: []
    m_IndexBuffer:
    m_VertexData:
      serializedVersion: 3
      m_VertexCount: 0
      m_Channels: []
      m_DataSize: 0
      _typelessdata:
    m_Bindpose: []
    textureRect:
      serializedVersion: 2
      x: 0
      y: 0
      width: 0
      height: 0
    textureRectOffset: {x: 0, y: 0}
    atlasRectOffset: {x: 0, y: 0}
    settingsRaw: 0
    uvTransform: {x: 0, y: 0, z: 0, w: 0}
    downscaleMultiplier: 0
  m_PhysicsShape: []
  m_Bones: []
  m_SpriteID:
```

The `spriteSheet` array of `ArtifactAtlas.png.meta` is empty in this version.

I guess it is related to the sprite export format.
I couldn't find the `outline` information in other files.

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/9430960/AssetRipper.log)
